-- Create valid_units table to store all valid unit numbers
CREATE TABLE IF NOT EXISTS valid_units (
    id SERIAL PRIMARY KEY,
    unit_number VARCHAR(3) NOT NULL UNIQUE,
    building VARCHAR(1) NOT NULL,
    floor VARCHAR(1) NOT NULL,
    unit_letter VARCHAR(1) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert all valid unit numbers
INSERT INTO valid_units (unit_number, building, floor, unit_letter) VALUES
-- Building A
('A1A', 'A', '1', 'A'),
('A1B', 'A', '1', 'B'),
('A1C', 'A', '1', 'C'),
('A1D', 'A', '1', 'D'),
('A1E', 'A', '1', 'E'),
('A1F', 'A', '1', 'F'),
('A1G', 'A', '1', 'G'),
('A1H', 'A', '1', 'H'),
('A1J', 'A', '1', 'J'),
('A1K', 'A', '1', 'K'),
('A1L', 'A', '1', 'L'),
('A1M', 'A', '1', 'M'),
('A1N', 'A', '1', 'N'),
('A1P', 'A', '1', 'P'),
('A1Q', 'A', '1', 'Q'),
('A1R', 'A', '1', 'R'),
('A1S', 'A', '1', 'S'),
('A1T', 'A', '1', 'T'),
('A1U', 'A', '1', 'U'),
('A1V', 'A', '1', 'V'),
('A2A', 'A', '2', 'A'),
('A2B', 'A', '2', 'B'),
('A2C', 'A', '2', 'C'),
('A2D', 'A', '2', 'D'),
('A2E', 'A', '2', 'E'),
('A2F', 'A', '2', 'F'),
('A2G', 'A', '2', 'G'),
('A2H', 'A', '2', 'H'),
('A2J', 'A', '2', 'J'),
('A2K', 'A', '2', 'K'),
('A2L', 'A', '2', 'L'),
('A2M', 'A', '2', 'M'),
('A2N', 'A', '2', 'N'),
('A2P', 'A', '2', 'P'),
('A2Q', 'A', '2', 'Q'),
('A2R', 'A', '2', 'R'),
('A2S', 'A', '2', 'S'),
('A2T', 'A', '2', 'T'),
('A2U', 'A', '2', 'U'),
('A2V', 'A', '2', 'V'),
('A3A', 'A', '3', 'A'),
('A3B', 'A', '3', 'B'),
('A3C', 'A', '3', 'C'),
('A3D', 'A', '3', 'D'),
('A3E', 'A', '3', 'E'),
('A3F', 'A', '3', 'F'),
('A3G', 'A', '3', 'G'),
('A3H', 'A', '3', 'H'),
('A3J', 'A', '3', 'J'),
('A3K', 'A', '3', 'K'),
('A3L', 'A', '3', 'L'),
('A3M', 'A', '3', 'M'),
('A3N', 'A', '3', 'N'),
('A3P', 'A', '3', 'P'),
('A3Q', 'A', '3', 'Q'),
('A3R', 'A', '3', 'R'),
('A3S', 'A', '3', 'S'),
('A3T', 'A', '3', 'T'),
('A3U', 'A', '3', 'U'),
('A3V', 'A', '3', 'V'),
-- Building B
('B1A', 'B', '1', 'A'),
('B1B', 'B', '1', 'B'),
('B1C', 'B', '1', 'C'),
('B1D', 'B', '1', 'D'),
('B1E', 'B', '1', 'E'),
('B1F', 'B', '1', 'F'),
('B1G', 'B', '1', 'G'),
('B1H', 'B', '1', 'H'),
('B2A', 'B', '2', 'A'),
('B2B', 'B', '2', 'B'),
('B2C', 'B', '2', 'C'),
('B2D', 'B', '2', 'D'),
('B2E', 'B', '2', 'E'),
('B2F', 'B', '2', 'F'),
('B2G', 'B', '2', 'G'),
('B2H', 'B', '2', 'H'),
('B3A', 'B', '3', 'A'),
('B3B', 'B', '3', 'B'),
('B3C', 'B', '3', 'C'),
('B3D', 'B', '3', 'D'),
('B3E', 'B', '3', 'E'),
('B3F', 'B', '3', 'F'),
('B3G', 'B', '3', 'G'),
('B3H', 'B', '3', 'H'),
('B4A', 'B', '4', 'A'),
('B4B', 'B', '4', 'B'),
('B4C', 'B', '4', 'C'),
('B4D', 'B', '4', 'D'),
('B4E', 'B', '4', 'E'),
('B4F', 'B', '4', 'F'),
('B4G', 'B', '4', 'G'),
('B4H', 'B', '4', 'H'),
('B5A', 'B', '5', 'A'),
('B5B', 'B', '5', 'B'),
('B5C', 'B', '5', 'C'),
('B5D', 'B', '5', 'D'),
('B5E', 'B', '5', 'E'),
('B5F', 'B', '5', 'F'),
('B5H', 'B', '5', 'H'),
-- Building C
('C1A', 'C', '1', 'A'),
('C1B', 'C', '1', 'B'),
('C1C', 'C', '1', 'C'),
('C1D', 'C', '1', 'D'),
('C1E', 'C', '1', 'E'),
('C1F', 'C', '1', 'F'),
('C1G', 'C', '1', 'G'),
('C2A', 'C', '2', 'A'),
('C2B', 'C', '2', 'B'),
('C2C', 'C', '2', 'C'),
('C2D', 'C', '2', 'D'),
('C2E', 'C', '2', 'E'),
('C2F', 'C', '2', 'F'),
('C2G', 'C', '2', 'G'),
('C3A', 'C', '3', 'A'),
('C3B', 'C', '3', 'B'),
('C3C', 'C', '3', 'C'),
('C3D', 'C', '3', 'D'),
('C3E', 'C', '3', 'E'),
('C3F', 'C', '3', 'F'),
('C3G', 'C', '3', 'G'),
('C4A', 'C', '4', 'A'),
('C4B', 'C', '4', 'B'),
('C4C', 'C', '4', 'C'),
('C4D', 'C', '4', 'D'),
('C4E', 'C', '4', 'E'),
('C4F', 'C', '4', 'F'),
('C4G', 'C', '4', 'G'),
('C5A', 'C', '5', 'A'),
('C5B', 'C', '5', 'B'),
('C5C', 'C', '5', 'C'),
('C5D', 'C', '5', 'D'),
('C5E', 'C', '5', 'E'),
('C5F', 'C', '5', 'F'),
('C5G', 'C', '5', 'G'),
-- Building D
('D1A', 'D', '1', 'A'),
('D1B', 'D', '1', 'B'),
('D1C', 'D', '1', 'C'),
('D1D', 'D', '1', 'D'),
('D1E', 'D', '1', 'E'),
('D1F', 'D', '1', 'F'),
('D2A', 'D', '2', 'A'),
('D2B', 'D', '2', 'B'),
('D2C', 'D', '2', 'C'),
('D2D', 'D', '2', 'D'),
('D2E', 'D', '2', 'E'),
('D2F', 'D', '2', 'F'),
('D3A', 'D', '3', 'A'),
('D3B', 'D', '3', 'B'),
('D3C', 'D', '3', 'C'),
('D3D', 'D', '3', 'D'),
('D3E', 'D', '3', 'E'),
('D3F', 'D', '3', 'F'),
('D4A', 'D', '4', 'A'),
('D4B', 'D', '4', 'B'),
('D4C', 'D', '4', 'C'),
('D4D', 'D', '4', 'D'),
('D4E', 'D', '4', 'E'),
('D4F', 'D', '4', 'F'),
('D5A', 'D', '5', 'A'),
('D5B', 'D', '5', 'B'),
('D5C', 'D', '5', 'C'),
('D5D', 'D', '5', 'D'),
('D5E', 'D', '5', 'E'),
('D5F', 'D', '5', 'F');

-- Enable Row Level Security
ALTER TABLE valid_units ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all authenticated users to read valid units
CREATE POLICY "Allow authenticated users to read valid units" ON valid_units
    FOR SELECT TO authenticated
    USING (true);

-- Create index for faster lookups
CREATE INDEX idx_valid_units_unit_number ON valid_units(unit_number);

-- Add comment to table
COMMENT ON TABLE valid_units IS 'Table containing all valid unit numbers for the property management system';