// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvqojgifgevrwicyhmvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2cW9qZ2lmZ2V2cndpY3lobXZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MTcwNjQsImV4cCI6MjA3MjA5MzA2NH0.rr5tDkJOz3H5N_UX7dLbEpVUVK0K1n7ExwUhEU7eqX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Ensure a single client instance across HMR reloads
declare global {
  // eslint-disable-next-line no-var
  var __supabase__: ReturnType<typeof createClient<Database>> | undefined;
}

const client = globalThis.__supabase__ ?? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Use a unique storage key for this app to avoid cross-app collisions
    storageKey: 'spr-vicecity-auth'
  }
});

if (!globalThis.__supabase__) {
  globalThis.__supabase__ = client;
}

export const supabase = client;